config:
  - application: "application.json"

application:
  - name: "{{ .Env.AppName }}"
  - rumEnabled: "true"
  - capturePercentage: "100"
  
application.preproduction:
  - rumEnabled: "true"
  - capturePercentage: "100"
  
application.production:
  - rumEnabled: "true"
  - capturePercentage: "5"
